---
title: "Mortality survey"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(knitr)
library(epireports)
library(survey)
```

```{r, message=FALSE}
# study_data_raw <- readxl::read_excel("...")
study_data_raw <- outbreaks::fluH7N9_china_2013

study_data_cleaned <- study_data_raw %>%
  # some cleaning
  mutate(age_in_years = as.integer(age),
         age_group = cut(age_in_years, breaks = seq(0, 90, 5), right = FALSE),
         sex = gender,
         symp_Tuberculosis = runif(n()) < 0.5,
         symp_Cancer = runif(n()) < 0.01,
         symp_Mumps = runif(n()) < 0.1,
         died = outcome == "Death") %>%
  filter(!is.na(sex))
```


# Introduction

# Study Design 

# Sample Size and Sampling methods

## Sample Size

```{r}
size <- sample_size(population_size = 10000,
                    precision = 0.005, 
                    design_effect = 1.5, 
                    expected_prevalence = 0.005)
size
```

```{r}
sample_size_households(size, 
                       avg_hh = 5, 
                       prop_under_5 = 0.15, 
                       frac_6_59 = 0.9, 
                       non_response_rate = 0.03)

```


## Sampling

### Random sampling

```{r}
# Insert some code to generate a random number sequence
```

### Cluster sampling

```{r}
# Insert some example code to do cluster sampling
```

# Study Findings


```{r}
# we first need to create a survery design that reflects the study
suvery_design <- svydesign(
  ids = ~1, # no cluster ids
  weights = NULL, #no sampling weights in this example
  data = study_data_cleaned
)
```


## Demographics

```{r}
plot_age_pyramid(study_data_cleaned)
```

## Morbitity

```{r}
# symptoms start with sym_

cols <- colnames(study_data_cleaned)
symptom_columns <- cols[grepl(pattern = "^sym", x = cols)]

survey_ciprop_foreach_binary_variable(design = suvery_design, 
                                      variables = symptom_columns) %>%
  knitr::kable()
```



## Mortality


```{r}
suvery_ciprob(suvery_design, "died") %>%
  knitr::kable()
```

```{r}
suvery_ciprob_stratified(suvery_design, "died", "age_group") %>%
  kable()
```


# Conclusions

# Recommendations

# References

