#' MSF data dictionaries and dummy datasets
#' This function reads in MSF data dictioanries and produces randomised datasets based these
#' @param disease Specify which disease you would like to use.
#' Currently supports "Cholera", "Measles" and "Meningitis".
#' @param varnames Specify name of column that contains varnames.
#' Currently default set to "Item".
#' (this can probably be deleted once dictionaries standardise)
#' @param numcases For fake data, specify the number of cases you want (default is 300)
#' @param tibble Return data dictionary as a tidyverse tibble (default is TRUE)
#' @import rio
#' @import epitrix
#' @import dplyr
#' @export


# function to
msf_dict <- function(name = "MSF-outbreak-dict.xls", disease, tibble = TRUE) {

  # get excel file path (need to specify the file name)
  path <- system.file("extdata", name, package = "sitrep")

  # read in data set - pasting the disease name for sheet
  dat_dict <- rio::import(path, which = paste0(disease, "_content"))

  # clean col names
  colnames(dat_dict) <- epitrix::clean_labels(colnames(dat_dict))

  # clean future var names (shortname_export)
  dat_dict$shortname_export <- epitrix::clean_labels(dat_dict$shortname_export)

  # DATA CLEANING
  # (CAN EVENTUALLY BE DELETED WHEN DICTIONARIES STABILISE)
  # 3 types added to - BOOLEAN, TRUE_ONLY and ORGANISATION-UNIT
  NO_OPTS   <- is.na(dat_dict$options)
  NO_X1     <- is.na(dat_dict$x_1)
  BOOL      <- dat_dict$value_type == "BOOLEAN"
  TRUE_ONLY <- dat_dict$value_type == "TRUE_ONLY"
  ORG_UNIT  <- dat_dict$value_type == "ORGANISATION_UNIT"

  # Grab the location of the options column
  OCOL      <- which(names(dat_dict) == "options")
  dat_dict[NO_OPTS & BOOL, OCOL]   <- "Yes"
  dat_dict[NO_X1 & BOOL, OCOL + 1] <- "No"


  dat_dict[NO_OPTS & TRUE_ONLY, OCOL]   <- "TRUE"
  dat_dict[NO_X1 & TRUE_ONLY, OCOL + 1] <- "NA"



  dat_dict[NO_OPTS & ORG_UNIT, OCOL]   <- "Hospital"
  dat_dict[NO_X1 & ORG_UNIT, OCOL + 1] <- "Clinic"
  dat_dict[NO_X1 & ORG_UNIT, OCOL + 2] <- "Health post"

  # return a tibble
  if (tibble == TRUE) {
    dat_dict <- tibble::as_tibble(dat_dict)
  }

  # return dictionary dataset
  dat_dict

}




gen_data <- function(disease, varnames = "shortname_export", numcases = 300) {

  # Three datasets:
  # 1) dat_dict = msf data dicationary generated by (msf_dict)
  # 2) dat_output = formatting of data dictionary to make use for sampling
  # 3) dis_output = disease dataset generated from sampling (exported)

  # get msf disease specific data dictionary
  dat_dict <- msf_dict(disease = disease, tibble = FALSE)

  # drop extra columns (keep after varnames column to retain contents of vars)
  varcol <- which(names(dat_dict) == varnames)
  dat_output <- dat_dict[, seq(from = varcol, to = length(dat_dict)), drop = FALSE]
  # drop value type
  dat_output$value_type <- NULL

  # use the var names as rows
  row.names(dat_output) <- dat_output[[varnames]]
  # remove the var names column
  dat_output <- dat_output[-1]
  # flip the dataset
  dat_output <- data.frame(t(dat_output))
  # remove rownames
  row.names(dat_output) <- NULL
  # # clean resulting labels
  # colnames(dat_output) <- epitrix::clean_labels(colnames(dat_output))

  # define variables that do not have any contents in the data dictionary
  empties <- names(dat_output[ , which(apply(!is.na(dat_output), FUN = sum, MARGIN = 2) == 0)])

  # create a NEW empty dataframe with the names from the data dictionary
  dis_output <- data.frame(matrix(ncol = ncol(dat_output), nrow = numcases) )
  colnames(dis_output) <- colnames(dat_output)

  # take samples for vars with defined options (non empties)
  dis_output[, !names(dat_output) %in% empties] <- apply(dat_output[, !names(dat_output) %in% empties],
                                                         MARGIN = 2,
                                                         function(x) sample(x[!is.na(x)],
                                                                            numcases, replace = TRUE))

  # Use data dicationary to define which vars are dates
  datevars <- dat_dict$shortname_export[dat_dict$value_type == "DATE"]
  # sample between two dates
  dis_output[ , datevars] <- replicate(length(datevars),
                                       sample(seq(as.Date("2018-01-01"), as.Date("2018-04-30"),
                                                  by = "day"), numcases, replace = TRUE))
  dis_output[ , datevars] <- lapply(dis_output[ , datevars], function(x) as.Date(x, origin = "1960-10-01"))



  # Patient identifiers
  dis_output$case_number <- paste0("A", 1:numcases)

  # treatment side facility
  dis_output$treatment_facility_site <- sample(paste0("Site ", 1:50),
                                               numcases, replace = TRUE)

  # age_years
  # sample 0:100
  dis_output$age_years <- sample(0:100,
                                 numcases, replace = TRUE)

  # age_month
  dis_output$age_months <- dis_output$age_years * 12
  dis_output$age_months[dis_output$age_years == 0] <- sample(0:12,
                                                             length(dis_output$age_months[dis_output$age_years == 0]),
                                                             replace = TRUE)


  # age_days
  dis_output$age_days <- dis_output$age_years * 365
  dis_output$age_days[dis_output$age_years == 0 &
                      dis_output$age_months > 0] <- 30 * dis_output$age_months[dis_output$age_years == 0 &
                      dis_output$age_months > 0]
                    dis_output$age_days[dis_output$age_years == 0 &
                                        dis_output$age_months == 0] <- sample(0:30,
                                                                              length(dis_output$age_days[dis_output$age_years == 0 &
                                                                                     dis_output$age_months == 0]),
                                                                              replace = TRUE)


                    if (disease == "Cholera") {
                      dis_output$ors_consumed_litres <- sample(1:10, numcases, replace = TRUE)
                      dis_output$iv_fluids_received_litres <- sample(1:10, numcases, replace = TRUE)
                    }

                    # return dataset as a tibble
                    dplyr::as_tibble(dis_output)

}




